CREATE TABLE room
(
    id         VARCHAR NOT NULL PRIMARY KEY,
    frozen     BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    state      jsonb NOT NULL DEFAULT '{}'
);

CREATE TABLE player
(
    id         VARCHAR NOT NULL PRIMARY KEY,
    name       VARCHAR NOT NULL,
    room_id    VARCHAR NOT NULL REFERENCES room (id) ON UPDATE CASCADE ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);

ALTER TABLE room
    ADD COLUMN owner_id VARCHAR NOT NULL REFERENCES player (id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE room
    ADD COLUMN turn_player_id VARCHAR DEFAULT NULL REFERENCES player (id) DEFERRABLE INITIALLY DEFERRED;
